spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${DKB-REDIS-HOST}
      port: ${DKB-REDIS-PORT}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
app:
  shortUrlBase: ${APP_SHORT_URL_BASE}
  shortCodeLength: ${APP_SHORT_CODE_LENGTH}