spring:
  datasource:
    url: jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  cache:
    type: simple
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework.cache: DEBUG
app:
  shortUrlBase: http://localhost:8080
  shortCodeLength: 6